#!/bin/sh

set -e

#Database directories ownership and permissions
if [ ! -d "/var/lib/a2d/" ]; then
    mkdir -p /var/lib/a2d/
fi

if [ ! -d "/var/lib/a2d/dbs" ]; then
    mkdir -p /var/lib/a2d/dbs
    sudo chown -R a2d:a2d /var/lib/a2d
fi

#User info directory ownership and permissions
sudo chown a2d:a2d /etc/a2d
sudo chmod -R +x /etc/a2d

#Program main directory ownership and permissions
sudo chown -R a2d:a2d /usr/bin/a2d
sudo chmod -R +x /usr/bin/a2d

#Set for system services under a2d
sudo chown a2d:a2d /lib/systemd/system/a2d_core.service
sudo chmod 644 /lib/systemd/system/a2d_core.service

sudo chown a2d:a2d /lib/systemd/system/a2d_core.timer
sudo chmod 644 /lib/systemd/system/a2d_core.timer

sudo chown a2d:a2d /usr/bin/a2d.sh
sudo chmod 755 /usr/bin/a2d.sh

exit 0
