#!/bin/sh

# Remove the user and associated group
sudo deluser --system a2d

# Check if start_a2d service is running
echo "Stopping a2d services."

sudo systemctl stop a2d_core.timer
sudo systemctl disable a2d_core.timer

sudo systemctl stop a2d_core.service
sudo systemctl disable a2d_core.service

# Delete leftover files
rm -r /usr/bin/a2d
rm -r /etc/a2d
rm -r /var/lib/a2d

exit 0
