#!/bin/sh

set -e

#DEBHELPER#

# Create the system user with no login shell
if id a2d; then
    echo "a2d user exist"
else
    adduser --system --group --no-create-home --home /nonexistent --shell /usr/sbin/nologin --disabled-password a2d
fi

# Wrapper script path for gunicorn due to unavilability of apt gu in system resource
WRAPPER_SCRIPT="/usr/local/bin/gunicorn_wrapper"

# Wrapper script content
WRAPPER_CONTENT="#!/bin/sh\necho \"Wrapper script is executing.\"\n/usr/bin/python3 -m gunicorn \"\$@\"\n"

# Create the wrapper script
echo "$WRAPPER_CONTENT" | tee "$WRAPPER_SCRIPT"

# Set execute permissions for the wrapper script
chmod +x "$WRAPPER_SCRIPT"

# Continue with package installation
exit 0
