#!/bin/sh

# Create the system user with no login shell
adduser --system --group --no-create-home --shell /usr/sbin/nologin --disabled-password a2d > /dev/null 2>&1

# Wrapper script path for gunicorn due to unavilability of apt gu in system resource
WRAPPER_SCRIPT="/usr/local/bin/gunicorn_wrapper"

# Wrapper script content
WRAPPER_CONTENT="#!/bin/sh\necho \"Wrapper script is executing.\"\n/usr/bin/python3 -m gunicorn \"\$@\"\n"

# Create the wrapper script
echo "$WRAPPER_CONTENT" | sudo tee "$WRAPPER_SCRIPT" > /dev/null

# Set execute permissions for the wrapper script
sudo chmod +x "$WRAPPER_SCRIPT"

# Continue with package installation
exit 0
