#!/bin/sh

set -e

#DEBHELPER#

#Remove sudo permission for a2d
if [ -e "/etc/sudoers.d/a2d_privileges*" ]; then
    rm /etc/sudoers.d/a2d_privileges*
fi

# Backup corn if upgrade
crontab -u a2d -l > /etc/a2d/a2d_crontab.txt
